### ISSUE TITLE
Does it work with hooks?

### ISSUE THREAD

**Issue by capaj** [oslabs-beta/reactime#111]
Would be nice to put this info in the readme

**Comment by rydang** [comment]
Currently, Reactime doesn't work with hooks. Stateful components only. 

> One important thing to note. This devtool is for React apps using only stateful components and prop drilling. If you're using Redux, Hooks, Context, or functional components, this devtool will not function on your app.

Hooks and functional components is definitely something we'd like to support in the future.

**Comment by RajeebTheGreat** [comment]
Hi @capaj,

We just released Reactime 3.0 which supports Hooks as well as Context API. Update both the npm package and Chrome extension and let me know if it works for you.

**Comment by mikestaub** [comment]
I just tested it but it doesn't seem to work with hooks. Do you have an example I can view?
